---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: podinfo
  namespace: infra
spec:
  interval: 168h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/stefanprodan/charts/podinfo
  ref:
    semver: ">= 6.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo3
  namespace: infra
spec:
  suspend: true # *** SUSPEND / DISABLE APP ***
  interval: 168h
  chartRef:
    kind: OCIRepository
    name: podinfo
    namespace: infra
  values:
    enabled: false
    extraEnvs:
      - name: RD_TEST_ENV_VAR
        value: "Testing RD VAR"
      - name: RD_TEST_ENV_DOMAIN
        value: "Domain: ${SECRET_DOMAIN}"
      - name: RD_TEST_ENV_ENC
        valueFrom:
          secretKeyRef:
            name: podinfo3-secret
            key: test-token
    service:
      externalPort: &port 80
    ingress:
      enabled: true
      className: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
      hosts:
        - host: &host "podinfo3.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
              service:
                name: prefixpath2
                port:
                  number: *port
      tls:
        - enabled: true
          hosts:
            - *host
    podAnnotations:
      secret.reloader.stakater.com/reload: podinfo3-secret