---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: infra
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/stefanprodan/charts/podinfo
  ref:
    semver: ">= 6.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: infra
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: podinfo
    namespace: default
  values:
    service:
      externalPort: &port 80
    ingress:
      enabled: true
      className: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
      hosts:
        - host: &host "podinfo3.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
              service:
                name: prefixpath2
                port:
                  number: *port
      tls:
        - enabled: true
          hosts:
            - *host