---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo3
  namespace: infra
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '>4.0.0'
  interval: 24h0m0s
  values:
    service:
      externalPort: 80
    ingress:
      enabled: true
      className: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
      hosts:
        - host: &host "podinfo3.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
              service:
                name: prefixpath2
                port:
                  number: 80
      tls:
        - enabled: true
          hosts:
            - *host