---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: n8n-secret
    template:
      engineVersion: v2
      data:
        # Database
        POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        POSTGRES_USER: "{{ .n8n_postgres_user }}"
        POSTGRES_PASSWORD: "{{ .n8n_postgres_password }}"
        POSTGRES_SUPER_PASS: "{{ .cloudnative_pg_password }}"
        # Encryption Key
        N8N_ENCRYPTION_KEY: "{{ .n8n_encryption_key }}"
        # SMTP Configuration
        N8N_SMTP_HOST: "{{ .n8n_smtp_host }}"
        N8N_SMTP_PORT: "{{ .n8n_smtp_port }}"
        N8N_SMTP_USER: "{{ .n8n_smtp_user }}"
        N8N_SMTP_PASS: "{{ .n8n_smtp_pass }}"
        N8N_SMTP_SENDER: "{{ .n8n_smtp_sender }}"
  dataFrom:
    - extract:
        key: n8n
    - extract:
        key: cloudnative-pg
# Test