---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: cnpg
#   namespace: cloudnative-pg
# spec:
#   interval: 1h
#   chart:
#     spec:
#       chart: cloudnative-pg
#       version: "0.27.0"
#       sourceRef:
#         kind: HelmRepository
#         name: cloudnative-pg
#         namespace: database
#       interval: 12h
# ---
# # yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: OCIRepository
# metadata:
#   name: cloudnative-pg
# spec:
#   interval: 1h
#   layerSelector:
#     mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
#     operation: copy
#   ref:
#     tag: 0.27.0
#   url: oci://ghcr.io/szinn/charts-mirror/cloudnative-pg
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.27.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      interval: 12h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    crds:
      create: true
    # config:
    #   data:
    #     INHERITED_ANNOTATIONS: kyverno.io/ignore
    # monitoring:
    #   podMonitorEnabled: false
    #   grafanaDashboard:
    #     create: true
    resources:
      requests:
        cpu: 50m
        memory: 192Mi
      limits:
        memory: 512Mi