---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-secret
  namespace: media
spec:
  dataFrom:
    - extract:
        key: media
    - extract:
        key: sonarr
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword