---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app organizr
  namespace: flux-system
spec:
  targetNamespace: infra
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: "./kubernetes/apps/infra/organizr/app"
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  # wait: false # no flux ks dependents
  interval: 30m
  timeout: 5m
  # dependsOn:
  #   - name: external-secrets
  #   - name: rook-ceph-cluster
  #   - name: cloudnative-pg-cluster