---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homarr-secret
    template:
      engineVersion: v2
      data:
        # Database
        POSTGRES_DB: "homarr"
        POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        POSTGRES_USER: "{{ .homarr_postgres_user }}"
        POSTGRES_PASSWORD: "{{ .homarr_postgres_password }}"
        POSTGRES_SUPER_PASS: "{{ .cloudnative_pg_password }}"
        # Database URL for Homarr
        DB_URL: "postgresql://{{ .homarr_postgres_user }}:{{ .homarr_postgres_password }}@postgres-rw.database.svc.cluster.local:5432/homarr"
        # Encryption Key
        SECRET_ENCRYPTION_KEY: "{{ .homarr_secret_encryption_key }}"
  dataFrom:
    - extract:
        key: homarr
    - extract:
        key: cloudnative-pg
