---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homarr
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      homarr:
        containers:
          app:
            image:
              repository: ghcr.io/homarr-labs/homarr
              tag: v1.0.0
              pullPolicy: IfNotPresent
            env:
              TZ: "America/Los_Angeles"
              AUTH_PROVIDERS: "credentials"
              DISABLE_ANALYTICS: "true"
              # DATABASE_URL:
              #   valueFrom:
              #     secretKeyRef:
              #       name: homarr-secret
              #       key: DB_URL
              SECRET_ENCRYPTION_KEY:
                valueFrom:
                  secretKeyRef:
                    name: homarr-secret
                    key: SECRET_ENCRYPTION_KEY
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      app:
        controller: homarr
        ports:
          http:
            port: 7575
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "dash.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        existingClaim: homarr-config
        globalMounts:
          - path: /app/data/configs
      data:
        enabled: true
        existingClaim: homarr-data
        globalMounts:
          - path: /data