---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: photoprism-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: photoprism-secret
    template:
      engineVersion: v2
      data:
        POSTGRES_DB: photoprism
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_USER: "{{ .photoprism_postgres_user }}"
        POSTGRES_PASSWORD: "{{ .photoprism_postgres_password }}"
        POSTGRES_SUPER_PASS: "{{ .cloudnative_pg_password }}"
        PHOTOPRISM_ADMIN_PASSWORD: "{{ .photoprism_admin_password }}"
  dataFrom:
    - extract:
        key: photoprism
    - extract:
        key: cloudnative-pg
