---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      photoprism:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.2
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: photoprism-secret
        containers:
          app:
            image:
              repository: photoprism/photoprism
              tag: 20220121@sha256:8dd9e8e5290c8bf648d0e91ea8ef81038ffc8800ebf6322417682a0342e04065
              pullPolicy: IfNotPresent
            env:
              TZ: "America/Los_Angeles"
              HOME: /photoprism
              PHOTOPRISM_PUBLIC: "false"
              PHOTOPRISM_UID: "568"
              PHOTOPRISM_GID: "568"
              PHOTOPRISM_UMASK: "0022"
              # Database
              PHOTOPRISM_DATABASE_DRIVER: postgres
              PHOTOPRISM_DATABASE_SERVER: "postgres-rw.database.svc.cluster.local:5432"
              PHOTOPRISM_DATABASE_NAME: photoprism
              PHOTOPRISM_DATABASE_USER:
                valueFrom:
                  secretKeyRef:
                    name: photoprism-secret
                    key: POSTGRES_USER
              PHOTOPRISM_DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: photoprism-secret
                    key: POSTGRES_PASSWORD
              # Admin credentials
              PHOTOPRISM_ADMIN_USER: admin
              PHOTOPRISM_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: photoprism-secret
                    key: PHOTOPRISM_ADMIN_PASSWORD
              # Paths
              PHOTOPRISM_STORAGE_PATH: /assets/storage
              PHOTOPRISM_SIDECAR_PATH: /assets/sidecar
              PHOTOPRISM_CONFIG_PATH: /assets/config
              PHOTOPRISM_CACHE_PATH: /assets/cache
              PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
              PHOTOPRISM_IMPORT_PATH: /photoprism/import
              PHOTOPRISM_TEMP_PATH: /photoprism/temp
              PHOTOPRISM_BACKUP_PATH: /assets/backup
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: photoprism
        ports:
          http:
            port: 2342
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "photos.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      assets:
        enabled: true
        existingClaim: photoprism-assets
        globalMounts:
          - path: /assets
      originals:
        enabled: true
        existingClaim: photoprism-originals
        globalMounts:
          - path: /photoprism/originals
      import:
        enabled: true
        existingClaim: photoprism-import
        globalMounts:
          - path: /photoprism/import
      temp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /photoprism/temp