---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      paperless-ngx:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.2
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: paperless-ngx-secret
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.18.4@sha256:3421ebe06ed27662d014046cf5089e612de853aae0c676a2bc72f73b38080e57
              pullPolicy: IfNotPresent
            env:
              TZ: "America/Los_Angeles"
              PAPERLESS_TIME_ZONE: "America/Los_Angeles"
              PAPERLESS_PORT: "8000"
              PAPERLESS_URL: "https://docs.${SECRET_DOMAIN}"
              PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://docs.${SECRET_DOMAIN}"
              PAPERLESS_CORS_ALLOWED_HOSTS: "https://docs.${SECRET_DOMAIN}"
              PAPERLESS_OCR_LANGUAGE: "eng"
              PAPERLESS_OCR_LANGUAGES: "eng"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_CONSUMPTION_DIR: "/consume"
              PAPERLESS_DATA_DIR: "/data"
              PAPERLESS_MEDIA_ROOT: "/media"
              # Database
              PAPERLESS_DBHOST: "postgres-rw.database.svc.cluster.local"
              PAPERLESS_DBPORT: "5432"
              PAPERLESS_DBNAME: "paperless-ngx"
              PAPERLESS_DBUSER:
                valueFrom:
                  secretKeyRef:
                    name: paperless-ngx-secret
                    key: POSTGRES_USER
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-ngx-secret
                    key: POSTGRES_PASSWORD
              # Redis
              PAPERLESS_REDIS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-ngx-secret
                    key: REDIS_URL
              # Secrets
              PAPERLESS_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: paperless-ngx-secret
                    key: PAPERLESS_SECRET_KEY
              PAPERLESS_ADMIN_USER: "admin"
              PAPERLESS_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: paperless-ngx-secret
                    key: PAPERLESS_ADMIN_PASSWORD
            resources:
              requests:
                cpu: 1000m
                memory: 256Mi
              limits:
                memory: 2Gi
    #         securityContext:
    #           allowPrivilegeEscalation: false
    #           readOnlyRootFilesystem: false
    #           capabilities:
    #             drop:
    #               - ALL
    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 568
    #     runAsGroup: 568
    #     fsGroup: 568
    #     fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: paperless-ngx
        ports:
          http:
            port: 8000
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "docs.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        enabled: true
        existingClaim: paperless-ngx-data
        globalMounts:
          - path: /data
      media:
        enabled: true
        existingClaim: paperless-ngx-media
        globalMounts:
          - path: /media
      consume:
        enabled: true
        existingClaim: paperless-ngx-consume
        globalMounts:
          - path: /consume
      config:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config