---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
# tes
metadata:
  name: staging
  namespace: flux-system
spec:
  provider:
    onepassword:
      connectHost: http://10.13.37.70:9430
      vaults:
        "Home-Ops Default": 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token-staging
            key: token