---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo2
spec:
  suspend: true # *** SUSPEND / DISABLE APP ***
  interval: 168h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: internal-ingress-nginx
      namespace: network
  values:
    enabled: false
    controllers:
      app:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/stefanprodan/podinfo
              tag: 6.8.0
    # test
    service:
      # Configure a service for the main application
      app:
        controller: app
        type: ClusterIP
        ports:
          http:
            port: 9898
    ingress:
      # Configure an Ingress for the main application
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    # service:
    #   app:
    #     controller: podinfo
    #     ports:
    #       http:
    #         port: 9899
    # ingress:
    #   enabled: "true"
    #   ClassName: internal
    #   annotations:
    #     external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
    #   hosts:
    #     - host: &host "podinfo.${SECRET_DOMAIN}"
    #       paths:
    #         - path: /
    #           pathType: ImplementationSpecific
    #   tls:
    #     - hosts:
    #         - *host