---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: internal-ingress-nginx
      namespace: network
  values:
    controllers:
      podinfo:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/stefanprodan/podinfo
              tag: 6.8.0
            # env:
            #   HTTP_PORT: &port 80
            #   LOG_WITHOUT_NEWLINE: true
            #   LOG_IGNORE_PATH: /healthz
            #   PROMETHEUS_ENABLED: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: podinfo
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: podinfo
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: podinfo
#   namespace: infra
# spec:
#   interval: 10m
#   url: https://stefanprodan.github.io/podinfo
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: podinfo
#   namespace: infra
# spec:
#   interval: 10m
#   timeout: 5m
#   chart:
#     spec:
#       chart: podinfo
#       sourceRef:
#         kind: HelmRepository
#         name: podinfo
#       interval: 5m
#   releaseName: podinfo
#   values:
#     # ingress:
#     #   enabled: true
#     #   className: "internal"
#     #   annotations:
#     #     external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
#     #     # kubernetes.io/ingress.class: nginx
#     #     # kubernetes.io/tls-acme: "true"
#     #   hosts:
#     #     - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
#     #       paths:
#     #         - path: /
#     #           pathType: ImplementationSpecific
#     ingress:
#       app:
#       # test
#         className: internal
#         annotations:
#           external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
#         hosts:
#           - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
#             paths:
#               - path: /
#                 service:
#                   identifier: app
#                   port: http