apiVersion: v1
kind: Secret
metadata:
  name: source-secret
  namespace: flux-system
stringData:
  source-key: "my-secret"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example # Customisable
  namespace: flux-system
spec:
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - name: staging
      kind: ClusterSecretStore
  selector:
    secret:
      name: source-secret # Source Kubernetes secret
  data:
    - match:
        secretKey: source-key # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: 1pw-secret-name # 1Password item/secret name
          property: password         # (Optional) 1Password field type, default password
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          vault: ""            # Optional the vault the secret is going to be pushed to, defaults to the first defined vault in the (Cluster)SecretStore
          # tags: ["tag1", "tag2"]    # Optional metadata to be pushed with the secret