# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ASnN4Q/mtK49gnGYapoEG1EwFzEBrDc5naX8MtCODGrlFGm8Z8X4Kg==,iv:Dwrd+Xtwm1x2MrRj+1O4H17+bz/zhzgsZby3Easte4E=,tag:ZMyE7XK6Zaxtyv6o8RZvzA==,type:str]
sops:
  age:
    - recipient: age10n5er0p64d5w7vqtj2shx82muqlcc7zmdx2yl70zn3l4ts8ah9zqf2s4ld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YUxlRGpRVDZHTlY0VEpu
        YUNvT1NJSitpRHVNeDRlT3RCY005RVJZajBJCjViN0c2aVBDMUNKQ1RoY2xCMjN1
        OHVNL3VtVDQ1eHYzbVlzc3BJZTNJNkkKLS0tIC8zTklCcjVwK1FYUVJ0VXJTVSts
        TWNHRzdwcUZyekh6MWpzdnpRMkdvblEKLWGRuPGF+so+H7yxmxXo4w9U60GXJuYX
        IbBvxGJ4TTcyHzqpnAQSoAl68BDBJMqYKutFMatybcIGPt5uMmv9Zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-25T09:23:48Z"
  mac: ENC[AES256_GCM,data:HjM1T2QcEI22BNgLCe3ZeTT9r1i6iW7bc9gVhRNm9K1XWCLS3ju8PvtQzoTLYMhUd7gTZmEc02t/FtjzdJEmNq7ahysP9Hi9VPzjmrX0E6CjUz24WKYi7jE/b/yWyB1bOzVwhLjBegI8TkOv3cZV9atpAuDQD+49Rvbo5ahbr0Y=,iv:yvxy8CEUKKpuOpZU+ziI/EXtAtwkeX/BVeCjYxDd/bo=,tag:stpPVnv8v5sBB0Y3VYCtXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
