---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: matheusfm
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://matheusfm.dev/charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: httpbin2
spec:
  chart:
    spec:
      chart: httpbin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: matheusfm
  interval: 24h
  dependsOn:
    - name: internal-ingress-nginx
      namespace: network
  values:
    service:
      type: ClusterIP
      ports:
        port: 8080
    ingress:
      className: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
      hosts:
        - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: http
      tls:
        - hosts:
            - *host
    # service:
    #   app:
    #     controller: podinfo
    #     ports:
    #       http:
    #         port: 9899
    # ingress:
    #   enabled: "true"
    #   ClassName: internal
    #   annotations:
    #     external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
    #   hosts:
    #     - host: &host "podinfo.${SECRET_DOMAIN}"
    #       paths:
    #         - path: /
    #           pathType: ImplementationSpecific
    #   tls:
    #     - hosts:
    #         - *host




# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: podinfo
#   namespace: infra
# spec:
#   interval: 10m
#   url: https://stefanprodan.github.io/podinfo
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: podinfo
#   namespace: infra
# spec:
#   interval: 10m
#   timeout: 5m
#   chart:
#     spec:
#       chart: podinfo
#       sourceRef:
#         kind: HelmRepository
#         name: podinfo
#       interval: 5m
#   releaseName: podinfo
#   values:
#     # ingress:
#     #   enabled: true
#     #   className: "internal"
#     #   annotations:
#     #     external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
#     #     # kubernetes.io/ingress.class: nginx
#     #     # kubernetes.io/tls-acme: "true"
#     #   hosts:
#     #     - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
#     #       paths:
#     #         - path: /
#     #           pathType: ImplementationSpecific
#     ingress:
#       app:
#       # test
#         className: internal
#         annotations:
#           external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
#         hosts:
#           - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
#             paths:
#               - path: /
#                 service:
#                   identifier: app
#                   port: http




# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: podinfo
#   namespace: default
# spec:
#   interval: 10m
#   url: https://stefanprodan.github.io/podinfo
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: podinfo
#   namespace: default
# spec:
#   releaseName: podinfo
#   chart:
#     spec:
#       chart: podinfo
#       sourceRef:
#         kind: HelmRepository
#         name: podinfo
# #   interval: 50m
# #   install:
# #     remediation:
# #       retries: 3
# #   # Default values
# #   # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
#   values:
#     ingress:
#       enabled: true
#       className: external



            # env:
            #   HTTP_PORT: &port 80
            #   LOG_WITHOUT_NEWLINE: true
            #   LOG_IGNORE_PATH: /healthz
            #   PROMETHEUS_ENABLED: true
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /healthz
            #         port: &port 80
            #       initialDelaySeconds: 0
            #       periodSeconds: 10
            #       timeoutSeconds: 1
            #       failureThreshold: 3
            #   readiness: *probes
    #         securityContext:
    #           allowPrivilegeEscalation: false
    #           readOnlyRootFilesystem: true
    #           capabilities: { drop: ["ALL"] }
    #         resources:
    #           requests:
    #             cpu: 10m
    #           limits:
    #             memory: 64Mi
    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 65534
    #     runAsGroup: 65534
    #     seccompProfile: { type: RuntimeDefault }



    # serviceMonitor:
    #   app:
    #     serviceName: podinfo
    #     endpoints:
    #       - port: http
    #         scheme: http
    #         path: /metrics
    #         interval: 1m
    #         scrapeTimeout: 10s
    # service:
    #   enabled: true
    #   annotations: {}
    #   type: ClusterIP
    #   metricsPort: 9797
    #   httpPort: 9898
    #   externalPort: 9898
    #   grpcPort: 9999
    #   grpcService: podinfo
    #   nodePort: 31198