---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: matheusfm
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://matheusfm.dev/charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: httpbin2
spec:
  chart:
    spec:
      chart: httpbin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: matheusfm
  interval: 24h
  dependsOn:
    - name: internal-ingress-nginx
      namespace: network
  values:
    service:
      type: ClusterIP
      ports:
        port: 8080
    ingress:
      enabled: true
      className: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
      hosts:
        - host: &host "httpbin2.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: http
      tls:
        - hosts:
            - *host