---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
# tes
metadata:
  name: staging
spec:
  provider:
    onepassword:
      connectHost: http://10.13.37.70:9430
      vaults:
        "Home-Ops Default": 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token-staging
            key: token
# Example - Not used
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: vault-backend-global
# spec:
#   provider:
#     vault:
#       server: "https://vault.your-domain.com"
#       path: secret
#       version: v2
#       auth:
#         # points to a secret that contains a vault token
#         # https://www.vaultproject.io/docs/auth/token
#         tokenSecretRef:
#           name: "vault-token-global"
#           key: "token"
#           namespace: external-secrets