---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: staging
spec:
  provider:
    onepassword:
      connectHost: ${ONEPASSWORD_CONNECT_HOST}
      vaults:
        "Home-Ops Default": 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token-staging
            key: token
            namespace: external-secrets