---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  # Renamed for clarity, as it now points to the whole repository
  name: truecharts
  namespace: util
spec:
  type: oci
  interval: 15m
  # URL now points to the parent repository, not the specific chart
  url: oci://tccr.io/truecharts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: util
spec:
  interval: 1h
  chart:
    spec:
      # The chart name is required and now correctly appended to the repo URL
      chart: ntfy
      # version: "14.2.0"
      sourceRef:
        kind: HelmRepository
        # This now points to the 'truecharts' HelmRepository defined above
        name: truecharts
        namespace: util
  install:
    remediation:
      retries: -1