---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: organizr
  namespace: infra
spec:
  # suspend: true # *** SUSPEND / DISABLE APP ***
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: internal-ingress-nginx
      namespace: network
  values:
    # enabled: false
    controllers:
      app:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/organizr/organizr
              tag: latest
            env:
              TZ: America/Los_Angeles
              branch: v2-master
    service:
      app:
        controller: app
        type: ClusterIP
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      # Doesn't appear to be used, /var/www/data seems to be empty
      data:
        enabled: true
        existingClaim: organizr
        globalMounts:
          - path: /var/www/data
      # Config data stored at /config/www/organizr/data
      config:
        enabled: true
        existingClaim: organizr-config
        globalMounts:
          - path: /config